- name: install every 5 minutes cronjobs
  cron:
    name: "{{ item.name }}"
    minute: "*/5"
    job: "{{ item.job }}"
  loop: "{{ every_5_minutes_cronjobs }}" # this is the list of cronjob commands for every 5 minutes schedule
  when: every_5_minutes_cronjobs is defined # this condition ensures that the task only runs if the host_vars have this list defined

- name: install daily cronjobs
  cron:
    name: "{{ item.name }}"
    hour: "{{ item.hour | default('0') }}"
    job: "{{ item.job }}"
  loop: "{{ daily_cronjobs }}" # this is the list of cronjob commands for weekly schedule
  when: daily_cronjobs is defined # this condition ensures that the task only runs if the host_vars have this list defined

- name: install hourly cronjobs
  cron:
    name: "{{ item.name }}"
    special_time: hourly
    job: "{{ item.job }}"
  loop: "{{ hourly_cronjobs }}" # this is the list of cronjob commands for hourly schedule
  when: hourly_cronjobs is defined # this condition ensures that the task only runs if the host_vars have this list defined

- name: install weekly cronjobs
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.day | default('6') }}"
    hour: "{{ item.hour | default('0') }}"
    minute: "0"
    job: "{{ item.job }}"
  loop: "{{ weekly_cronjobs }}" # this is the list of cronjob commands for weekly schedule
  when: weekly_cronjobs is defined # this condition ensures that the task only runs if the host_vars have this list defined

- name: install reboot cronjobs
  cron:
    name: "{{ item.name }}"
    special_time: reboot
    job: "{{ item.job }}"
  loop: "{{ reboot_cronjobs }}" # this is the list of cronjob commands for reboot schedule
  when: reboot_cronjobs is defined # this condition ensures that the task only runs if the host_vars have this list defined