- name: Add Jellyfin apt key
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    state: present

- name: Add Jellyfin repository
  apt_repository:
    repo: deb [arch=amd64] https://repo.jellyfin.org/ubuntu {{ ansible_distribution_release }} main
    filename: jellyfin
    state: present

- name: Install jellyfin
  package:
    name: jellyfin

- name: Mount tmpfs for transcoding
  ansible.posix.mount:
    src: none
    path: /var/tmp/transcode
    opts: size=16G,nr_inodes=10k,mode=1755,uid=110,gid=118
    state: mounted
    fstype: tmpfs
