- name: Include Traefik variables
  include_vars: traefik.yml

- name: Create network
  docker_network:
    name: traefik
    internal: false
  become: true

- name: Create directory
  file:
    path: /opt/traefik
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Create config directory
  file:
    path: /opt/traefik/traefik/
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Create file provider directory
  file:
    path: /opt/traefik/traefik/conf
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/traefik/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart traefik
  become: true

- name: Install config
  template:
    src: files/traefik.yml
    dest: /opt/traefik/traefik/traefik.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart traefik
  become: true

- name: Install jellyfin provider
  template:
    src: files/file-provider-jellyfin.yml
    dest: /opt/traefik/traefik/conf/jellyfin.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart traefik
  become: true


- name: Install gitlab provider
  template:
    src: files/file-provider-gitlab.yml
    dest: /opt/traefik/traefik/conf/gitlab.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart traefik
  become: true
