ansible_user_pre: root
ansible_become_pass_pre: asdasd
ansible_port_pre: 22

ansible_user: ansible-worker
ansible_become_pass: ans1bl3manag3m3nt
ansible_port: 2278

proxmox_host_ip: 192.168.9.152
adguard_host_ip: 192.168.9.150
filesvr_host_ip: 192.168.9.153
mediasvr_host_ip: 192.168.9.154
proxy_host_ip: 192.168.9.155
privatevpn_host_ip: 192.168.9.156
portainer_host_ip: 192.168.9.151
nextcloud_host_ip: 192.168.9.157
logs_host_ip: 192.168.9.228
ansible_host_ip: 127.0.0.1
gitlab_host_ip: 192.168.9.159
tailscale_host_ip: 192.168.9.135
nebula_host_ip: 192.168.9.176
kub01_host_ip: 192.168.9.214
