- name: Include variables
  include_vars:
    dir: vars

- name: Create AIO directory
  file:
    path: /opt/aio
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Create photoprism directory
  file:
    path: /opt/photoprism
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install AIO compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/aio/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart aio
  become: true

- name: Install Photoprism compose file
  template:
    src: files/photoprism.yml
    dest: /opt/photoprism/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart photoprism
  become: true
