---
    - name: Daemon Reload
      become: true
      systemd:
        daemon_reload: yes

    - name: Start Elastic
      service:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Restart Elastic
      service:
        name: elasticsearch
        state: restarted

    - name: Start Logstash
      service:
        name: logstash
        state: started
        enabled: yes

    - name: Start Filebeat
      service:
        name: filebeat
        state: started
        enabled: yes

    - name: Start Kibana
      service:
        name: kibana
        state: started
        enabled: yes
