x-base: &base #define "base" as anchor key
  restart: always 
x-lsio: &lsio
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Kuala_Lumpur
x-internalbase: &internalbase
  <<: *base #calling "base" and pull its value
  networks:
    - internal
x-vpnbase: &vpnbase
  <<: *base
  network_mode: "service:vpn"
x-lsiobase: &local
  <<: *internalbase
  <<: *lsio
x-vpnlsiobase: &vpn
  <<: *vpnbase
  <<: *lsio
x-wg-port: &exposed_port
  ports:
    - 8080:8080 #qbittorrent
    - 7878:7878 #radarr
    - 8989:8989 #sonarr
    - 8686:8686 #lidarr
    - 6767:6767 #bazarr
    - 8787:8787 #readarr

version: "2.1"
services:
  vpn:
    image: ghcr.io/linuxserver/wireguard:{{ wireguard_ver }}
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped
    <<: *exposed_port
    <<: *local

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:{{ qbittorrent_ver }}
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - /mnt/downloads:/downloads
    network_mode: "service:vpn"
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:{{ prowlarr_ver }}
    container_name: prowlarr
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    <<: *local

  radarr:
    image: ghcr.io/linuxserver/radarr:{{ radarr_ver }}
    container_name: radarr
    volumes:
      - ./radarr:/config
      - /mnt/media/Movies:/media #optional
      - /mnt/downloads:/downloads #optional
    <<: *vpn

  sonarr:
    image: ghcr.io/linuxserver/sonarr:{{ sonarr_ver }}
    container_name: sonarr
    volumes:
      - ./sonarr:/config
      - /mnt/media/TV_Shows:/media #optional
      - /mnt/downloads:/downloads #optional
    <<: *vpn

  lidarr:
    image: ghcr.io/linuxserver/lidarr:{{ lidarr_ver }}
    container_name: lidarr
    volumes:
      - ./lidarr/config:/config
      - /mnt/media/Music:/media #optional
      - /mnt/downloads:/downloads #optional
    <<: *vpn

  bazarr:
    image: ghcr.io/linuxserver/bazarr:{{ bazarr_ver }}
    container_name: bazarr
    volumes:
      - ./bazarr/config:/config
      - /mnt/media/Movies:/media/movies #optional
      - /mnt/media/TV_Shows:/media/tv #optional
      - /mnt/downloads:/downloads
    <<: *vpn

  readarr:
    image: ghcr.io/linuxserver/readarr:{{ readarr_ver }}
    container_name: readarr
    volumes:
      - ./readarr/data:/config
      - /mnt/media/Books:/media #optional
      - /mnt/downloads:/downloads #optional
    <<: *vpn

  portainer:
    image: 'cr.portainer.io/portainer/agent'
    container_name: portainer_agent
    ports:
      - '9001:9001'
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'

networks:
  internal:
    external: true
