- name: Install main compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_default_user }}"
    validate: docker-compose -f %s config
  register: compose_file
  become: true

- name: trigger compose command
  command:
    chdir: /opt
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed
