- name: Include PrivateVPN variables
  include_vars:
    dir: vars

- name: Create PrivateVPN directory
  file:
    path: /{{ docker_user.name }}
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install PrivateVPN compose file
  template:
    src: files/PrivateVPN/docker-compose.yml.j2
    dest: /{{ docker_user.name }}/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  register: compose_file
  become: true

- name: Trigger PrivateVPN compose command
  shell:
    chdir: /{{ docker_user.name }}
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed

- name: Restart PrivateVPN stack in correct order
  shell:
    chdir: /{{ docker_user.name }}/scripts
    cmd: bash update_restart.sh restart
  when: compose_file.changed
