---
# tasks file for flask_web
- name: Install vim
  apt:
    name: vim
    state: present

- name: Create directory
  file:
    path: ~/.vim/pack/themes/start
    state: directory
  become: true

- name: git clone dracula theme
  git:
    repo: https://github.com/dracula/vim.git
    dest: ~/.vim/pack/themes/start/dracula
    clone: yes
    version: master

- name: Copy vimrc files
  copy:
    src: files/vimrc
    dest: /root/.vimrc
