---
version: "2.3"
services:
  traefik:
    image: traefik:v2.8
    user: "{{ docker_user.id }}"
    environment:
      - CF_DNS_API_TOKEN={{ cloudflare_api_token }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/traefik-logs:/var/log/traefik
      - ./traefik:/etc/traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - default
      - traefik

  certs:
    image: slocomptech/traefik-cert-extract:latest
    restart: unless-stopped
    networks: []
    volumes:
      - ./traefik:/data:ro
      - ./certs:/config/certs
    logging:
      driver: none

networks:
  traefik:
    external: true
