entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
    proxyProtocol:
      trustedIPs:
        - "{{ wireguard.cidr }}"
        - "{{ pve_hosts.internal_cidr }}"
  web-secure:
    address: :443
    http:
      tls:
        certresolver: le
        domains:
          - main: "{{ domain_name }}"
            sans: "*.{{ domain_name }}"

    proxyProtocol:
      trustedIPs:
        - "{{ wireguard.cidr }}"
        - "{{ pve_hosts.internal_cidr }}"
  traefik:
    address: :8080

ping: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    watch: true
    network: traefik
  file:
    directory: /etc/traefik/conf
    watch: true


api:
  dashboard: true
  insecure: true

certificatesResolvers:
  le:
    acme:
      email: "{{ letsencrypt_email }}"
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53

serversTransport:
  insecureSkipVerify: true

tls:
  options:
    default:
      minVersion: VersionTLS12

pilot:
  dashboard: false

experimental:
  hub: false

accessLog:
  filePath: "/var/log/traefik/access.log"
  filters:
    statusCodes:
      - "400-600"
