bootstrap-job:
  stage: deploy
  rules:
    - if: '$DEPLOY == "all"'
      when: manual
  before_script:
    !reference [.get_ansible_vault, before_script]
  script:
    - cd $CI_PROJECT_DIR/ansible && ansible-playbook main.yaml