docker-compose-proxy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  rules:
    - if: !reference [.default_rules, rules, if]
      changes:
        - ansible/roles/nginx/**/*
    - if: '$DEPLOY == "proxy"'
      when: manual
  before_script:
    !reference [.get_ansible_vault, before_script]
  script:
    - COMPOSE_FILE=main.yaml
    - HOST=Proxy
    - echo "Deploying reverse-proxy stack application..."
    - !reference [.ansible_playbook, script]
