variables:
  HOST: Portainer

docker-compose-mastery:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  rules:
    - if: !reference [.default_rules, rules, if]
      changes:
      - ansible/roles/traefik/**/*
      - ansible/roles/aio/**/*  
      - ansible/roles/adguard/**/*
    - if: '$DEPLOY == "portainer"'
      when: manual
  before_script:
    !reference [.get_ansible_vault, before_script]
  script:
    - COMPOSE_FILE=main.yaml
    - HOST=Portainer
    - echo "Deploying portainer aio stack...."
    - !reference [.ansible_playbook, script]

